origin/origin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^$', auth_views.login, {'template_name': 'login.html'}, name='login'),
]

origin/tasks/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from tasks.views import ListTasksView, CreateTaskView, EditTaskView, MarkDoneStatusView, MarkNotDoneStatusView, DeleteTaskView

urlpatterns = [
    url(r'^create/$', login_required(CreateTaskView.as_view()), name='create_new'),
    url(r'^edit/(?P<pk>[\d]+)$', login_required(EditTaskView.as_view()), name='edit'),
    url(r'^mark_done/(?P<pk>[\d]+)$', login_required(MarkDoneStatusView.as_view()), name='mark_done'),
    url(r'^mark_not_done/(?P<pk>[\d]+)$', login_required(MarkNotDoneStatusView.as_view()), name='mark_not_done'),
    url(r'^delete/(?P<pk>[\d]+)$', login_required(DeleteTaskView.as_view()), name='delete'),
    url(r'^todo/$', login_required(ListTasksView.as_view(hide_completed=True)), name='task_list_hide_completed'),
    url(r'^$', login_required(ListTasksView.as_view()), name='task_list'),
]

origin/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Task(models.Model):
    """A task in the todo list.
    """
    TODO_STATUS = 'T'
    COMPLETED_STATUS = 'C'
    DELETED_STATUS = 'D'
    STATUSES = (
        (TODO_STATUS, 'To Do'),
        (COMPLETED_STATUS, 'Done'),
        (DELETED_STATUS, 'Deleted'),
    )
    created_by = models.ForeignKey(User, related_name='created_tasks')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    completed_by = models.ForeignKey(User, related_name='completed_tasks', null=True)
    completed_at = models.DateTimeField(null=True)
    deleted_by = models.ForeignKey(User, related_name='deleted_tasks', null=True)
    deleted_at = models.DateTimeField(null=True)
    status = models.CharField(max_length=1, choices=STATUSES, default=TODO_STATUS)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    @property
    def is_done(self):
        """A property to tell us whether we should consider a task done or not based on its status
        """
        if self.status in [self.DELETED_STATUS, self.COMPLETED_STATUS]:
            return True
        return False

    def delete(self, user):
        """Custom delete method. We only want to mark tasks as deleted so that the history of the database makes sense
        """
        self.deleted_at = timezone.now()
        self.status = self.DELETED_STATUS
        self.deleted_by = user
        self.save()

origin/tasks/forms.py
from django.forms import ModelForm
from tasks.models import Task


class CreateTaskForm(ModelForm):
    """Custom create task form

    This form takes a user object when it is initialised.
    On form.save, we write that user to the  'created_by' field
    """
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.instance.created_by = self.user
        return super().save(*args, **kwargs)

    class Meta:
        model = Task
        fields = ['name', 'description']

origin/tasks/views.py
from django.views.generic import ListView, CreateView, UpdateView, RedirectView, DeleteView
from tasks.forms import CreateTaskForm
from tasks.models import Task
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils import timezone


class ListTasksView(ListView):
    """List view for all tasks.
    we always hide 'deleted' tasks.
    optionally hide completed tasks.
    """
    model = Task
    template_name = 'task_list.html'
    paginate_by = 30
    hide_completed = False
    queryset = Task.objects.exclude(status=Task.DELETED_STATUS)

    def get_queryset(self):
        if self.hide_completed:
            return Task.objects.exclude(status__in=[Task.DELETED_STATUS, Task.COMPLETED_STATUS])
        return Task.objects.exclude(status=Task.DELETED_STATUS)


class CreateTaskView(CreateView):
    """View for creating new tasks.
    """
    form_class = CreateTaskForm
    template_name = 'create_task.html'
    success_url = reverse_lazy('tasks:task_list')

    def get_form_kwargs(self):
        """Pass the logged in user to the form. This is safer than doing something
        nasty with hidden fields.
        """
        form_kwargs = super().get_form_kwargs()
        form_kwargs['user'] = self.request.user
        return form_kwargs


class EditTaskView(UpdateView):
    """View to allow editing of tasks.
    """
    model = Task
    template_name = 'edit_task.html'
    success_url = reverse_lazy('tasks:task_list')
    fields = ['name', 'description']

    def get_object(self):
        """We override get object here so we can pass it the logged in user.
        This ensures that users can only edit tasks they have created.
        """
        obj = get_object_or_404(Task, pk=self.kwargs['pk'], created_by=self.request.user)
        return obj


class BaseStatusToggleView(RedirectView):
    """Base view which updates a task's status.
    Both marking as Done and makring as Not Done share a lot of similar code
    This is DRYer
    """
    success_message = None

    def get_redirect_url(self):
        return reverse_lazy('tasks:task_list')

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(Task, pk=self.kwargs['pk'])
        self.update_task()
        self.object.save()
        messages.success(request, self.success_message)
        return HttpResponseRedirect(self.get_redirect_url())


class MarkDoneStatusView(BaseStatusToggleView):
    """Child view to mark a task as done.
    """
    success_message = 'Task marked as Done'

    def update_task(self):
        self.object.status = Task.COMPLETED_STATUS
        self.object.completed_at = timezone.now()
        self.object.completed_by = self.request.user


class MarkNotDoneStatusView(BaseStatusToggleView):
    """Child view to mark a task as Todo
    """
    success_message = 'Task marked as To Do'

    def update_task(self):
        self.object.status = Task.TODO_STATUS
        self.object.completed_at = None
        self.object.completed_by = None


class DeleteTaskView(DeleteView):
    """Delete view to mark a task as deleted.
    """
    model = Task
    success_url = reverse_lazy('tasks:task_list')
    template_name = 'delete_lender.html'

    def delete(self, request, *args, **kwargs):
        """Override this method, as we want to persist the object in the db for audit reasons.

        get_object_or_404 allows us to be confident that users may only delete tasks
        they themselves have created
        """
        self.object = get_object_or_404(Task, pk=self.kwargs['pk'], created_by=self.request.user)
        success_url = self.get_success_url()
        self.object.delete(user=request.user)
        return HttpResponseRedirect(success_url)

origin/tasks/templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<form class="form" method="post" action="{% url 'tasks:create_new' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-danger" type="submit">Add</button>
</form>
{% endblock content %}

origin/tasks/templates/edit_task.html
{% extends 'base.html' %}

{% block content %}
<form method="post" action="{% url 'tasks:edit' pk=object.pk %}">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-danger" type="submit">Save</button>
</form>
{% endblock content %}

origin/tasks/templates/login.html
{% extends 'base.html' %}

{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock %}

origin/tasks/templates/task_list.html
{% extends 'base.html' %}

{% block content %}
    {% for object in object_list %}

    <div class="row">
        <div class="col-md-2">{{ object.name }}</div>
        <div class="col-md-2">{{ object.description }}</div>
        <div class="col-md-2">{{ object.get_status_display }}</div>
        <div class="col-md-2">
            <button class="btn btn-primary {% if object.created_by != request.user %} disabled {% endif %}" href="{% url 'tasks:edit' pk=object.pk %}">Edit</button>
        </div>
        <div class="col-md-2">
            {% if object.is_done %}
                <form method="post" action="{% url 'tasks:mark_not_done' pk=object.pk %}">
                    {% csrf_token %}
                    <button class="btn btn-warn" type="submit">Mark not done</button>
                </form>
            {% else %}
                <form method="post" action="{% url 'tasks:mark_done' pk=object.pk %}">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">Mark done</button>
                </form>
            {% endif %}
        </div>
        <div class="col-md-2">
            <form method="post" action="{% url 'tasks:delete' pk=object.pk %}">
                {% csrf_token %}
                <button class="btn btn-danger {% if object.created_by != request.user %} disabled {% endif %}" type="submit">Delete</button>
            </form>
        </div>
    </div>
    {% endfor %}
{% endblock %}

origin/templates/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <header id="header" class="navbar">
        <div class="container">
            <ul class="nav nav-tabs offset-3">
                {% block header %}
                    {% include 'partials/header.html' %}
                {% endblock header %}
            </ul>
        </div>
        </header>
        <div id="content" class="row-fluid">
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </body>
</html>

origin/templates/partials/header.html
<li>
    <a href="{% url 'tasks:create_new' %}">Add new task</a>
</li>
<li>
    {% url 'tasks:task_list' as show_all %}
    {% if request.path == show_all %}
        <a href="{% url 'tasks:task_list_hide_completed' %}">Hide completed</a>
    {% else %}
        <a href="{% url 'tasks:task_list' %}">Show all</a>
    {% endif %}
</li>
<li>
    <a href="{% url 'logout' %}">Logout</a>
</li>